//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArithmosViewModels {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class ArithmosSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ArithmosSettings defaultInstance = ((ArithmosSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ArithmosSettings())));
        
        public static ArithmosSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGematria {
            get {
                return ((bool)(this["ShowGematria"]));
            }
            set {
                this["ShowGematria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOrdinal {
            get {
                return ((bool)(this["ShowOrdinal"]));
            }
            set {
                this["ShowOrdinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowReduced {
            get {
                return ((bool)(this["ShowReduced"]));
            }
            set {
                this["ShowReduced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSumerian {
            get {
                return ((bool)(this["ShowSumerian"]));
            }
            set {
                this["ShowSumerian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPrimes {
            get {
                return ((bool)(this["ShowPrimes"]));
            }
            set {
                this["ShowPrimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSquared {
            get {
                return ((bool)(this["ShowSquared"]));
            }
            set {
                this["ShowSquared"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMisparGadol {
            get {
                return ((bool)(this["ShowMisparGadol"]));
            }
            set {
                this["ShowMisparGadol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMisparShemi {
            get {
                return ((bool)(this["ShowMisparShemi"]));
            }
            set {
                this["ShowMisparShemi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectGematria {
            get {
                return ((bool)(this["SelectGematria"]));
            }
            set {
                this["SelectGematria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectOrdinal {
            get {
                return ((bool)(this["SelectOrdinal"]));
            }
            set {
                this["SelectOrdinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectReduced {
            get {
                return ((bool)(this["SelectReduced"]));
            }
            set {
                this["SelectReduced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectSumerian {
            get {
                return ((bool)(this["SelectSumerian"]));
            }
            set {
                this["SelectSumerian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectPrimes {
            get {
                return ((bool)(this["SelectPrimes"]));
            }
            set {
                this["SelectPrimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectSquared {
            get {
                return ((bool)(this["SelectSquared"]));
            }
            set {
                this["SelectSquared"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectMisparGadol {
            get {
                return ((bool)(this["SelectMisparGadol"]));
            }
            set {
                this["SelectMisparGadol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectMisparShemi {
            get {
                return ((bool)(this["SelectMisparShemi"]));
            }
            set {
                this["SelectMisparShemi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectEnglish {
            get {
                return ((bool)(this["SelectEnglish"]));
            }
            set {
                this["SelectEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectHebrew {
            get {
                return ((bool)(this["SelectHebrew"]));
            }
            set {
                this["SelectHebrew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectGreek {
            get {
                return ((bool)(this["SelectGreek"]));
            }
            set {
                this["SelectGreek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectMixed {
            get {
                return ((bool)(this["SelectMixed"]));
            }
            set {
                this["SelectMixed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAlphabet {
            get {
                return ((bool)(this["ShowAlphabet"]));
            }
            set {
                this["ShowAlphabet"] = value;
            }
        }
    }
}
